import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import {useRouter} from 'next/router'
import styles from '../styles/Home.module.css'
import {useAuthState} from 'react-firebase-hooks/auth'
import {auth, db} from '../firebase'
import firebase from 'firebase/compat/app'
import { useEffect, useState } from 'react'
import Center from '../components/Center'
export default function channels() {
  const router = useRouter()
  const [user] = useAuthState(auth)

  const logout = ()=>{
    firebase.auth().signOut().then(() => {
      // Sign-out successful.
    }).catch((error) => {
      // An error happened.
    });
  }

  const [channeldata, setchanneldata] = useState([]);
    useEffect(()=>{
        var url_string = window.location.href
        var url = new URL(url_string);
        var id = url.searchParams.get("id");
        console.log(id);
        db.collection("channels").doc(id).get().then(data=>{
            console.log(data.data());
            setchanneldata(data.data())
        })

    },[])
  
    return (
      <div className='bg-black h-screen overflow-hidden'>
        <Head>
          <title>Rhythmbox Online</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className='flex'>
          <Sidebar />
          {/* {user?<button className='text-white' onClick={logout} type="">{user.displayName}</button>:
          <button className='text-white' onClick={()=>{
            router.push('/login')
          }} type="">Login</button>
          } */}
          <Center >
            <p className='text-white text-7xl font-bold ml-20'>{channeldata.channelname}</p>
            <p className='text-white ml-20 text-3xl mt-4 font-semibold'>By {channeldata.ownername}</p>
          </Center>
        </main>
  
        <div>
          {/* Player */}
        </div>
      </div>
    )
  
}
