import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import {useRouter} from 'next/router'
import styles from '../styles/Home.module.css'
import {useAuthState} from 'react-firebase-hooks/auth'
import {auth} from '../firebase'
import firebase from 'firebase/compat/app'
import { useEffect } from 'react'
import Center from '../components/Center'
export default function Home() {
  const router = useRouter()
  const [user] = useAuthState(auth)

  const logout = ()=>{
    firebase.auth().signOut().then(() => {
      // Sign-out successful.
    }).catch((error) => {
      // An error happened.
    });
  }

  useEffect(()=>{
    if(!user){
      router.push('/login')
    }
  },[])
  
    return (
      <div className='bg-black h-screen overflow-hidden'>
        <Head>
          <title>Rhythmbox Online</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className='flex'>
          <Sidebar />
          
          <Center >
            <div className='grid grid-flow-row justify-center grid-cols-4'>
              <div>
                  <img className=' mx-auto mt-20 rounded-md h-40 w-40' src="https://upload.wikimedia.org/wikipedia/en/8/80/Ed_Sheeran_Perfect_Single_cover.jpg" alt="" />
                  <p className='text-white text-center mt-2 text-3xl font-semibold'>Song name</p>
                  <p className='text-white text-center mt-2 text-xl '>Author name</p>
              </div>
              

            </div>
              

          </Center>
        </main>
  
        <div>
          {/* Player */}
        </div>
      </div>
    )
  
}
