import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import {useRouter} from 'next/router'
import styles from '../styles/Home.module.css'
import {useAuthState} from 'react-firebase-hooks/auth'
import {auth, db} from '../firebase'
import firebase from 'firebase/compat/app'
import { useContext, useEffect, useState } from 'react'
import Center from '../components/Center'
import { ChannelRefreshContext } from '../contexts/ChannelRefreshContext'
import Player from '../components/Player'
import { PlayerContext } from '../contexts/PlayerContext'
export default function Home() {
  const router = useRouter()
  const [user] = useAuthState(auth)
  const [allsongs, setallsongs] = useState([]);
  const [player, setPlayer] = useContext(PlayerContext);
  const logout = ()=>{
    firebase.auth().signOut().then(() => {
      // Sign-out successful.
    }).catch((error) => {
      // An error happened.
    });
  }
  const [channelrefresh, setchannelrefresh] = useContext(ChannelRefreshContext);
  useEffect(()=>{
    var temp = []
    db.collection("songs").get().then(data=>{
      data.forEach(obj=>{
        temp = [...temp,{...obj.data(),id:obj.id}]
      })
      console.log(temp);
      setallsongs(temp)
    })
  },[channelrefresh])

  
    return (
      <div className='bg-black h-screen'>
        <Head>
          <title>Rhythmbox Online</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className='flex'>
          <Sidebar />
          
          <Center title="All Podcasts" >
            <div className='grid grid-flow-row justify-center grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
              {
                allsongs.map((obj,index)=>{
                  return(
                    <div key={obj.id} onClick={()=>{
                      setPlayer({...obj,index:index})
                    }}>
                    <img className=' mx-auto mt-20 rounded-md h-40 w-40' src={obj.thumbnailurl} alt="" />
                        <p className='text-white text-center mt-2 text-3xl font-semibold'>{obj.podcastname}</p>
                        <p className='text-white text-center mt-2 text-xl '>{obj.authorname}</p>
                    </div>
                  )
                })
              } 
              

            </div>
              

          </Center>
        </main>
  
        <div className='fixed bottom-0'>
          {/* Player */}
          <Player allsongs={allsongs} />
        </div>
      </div>
    )
  
}
